/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Main;
import Model.KMeansModel;
import Model.Setting;
import java.io.File;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.filechooser.FileSystemView;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;
import weka.core.Instances;
/**
 *
 * @author dttr2
 */
public class DataS extends javax.swing.JFrame {
    public Main main;
    /**
     * Creates new form DataS
     */
    public DataS(Main main) {
        initComponents();
        init();
        this.main=main;
    }

     void init() {
        Instances data = KMeansModel.data;
        DefaultTableModel tbModel1 = (DefaultTableModel) tbIP.getModel();
        tbModel1.setRowCount(0);
        int ipL = data.size();
        for (int i = 0; i < ipL; i++) {
            tbModel1.addRow(new Object[]{
                data.get(i).value(data.attribute("manhinh")),
                data.get(i).value(data.attribute("ram")),
                data.get(i).value(data.attribute("cpu")),
                data.get(i).value(data.attribute("gpu")),
                data.get(i).value(data.attribute("trongluong")),
                data.get(i).value(data.attribute("loaibonho")),
                data.get(i).value(data.attribute("dungluongbonho")),
                data.get(i).value(data.attribute("gia")),
                data.get(i).stringValue(data.attribute("name")),
                data.get(i).stringValue(data.attribute("class")),
                data.get(i).value(data.attribute("id"))
            });
        }
        lbTotal.setText(data.size()+"");
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tbIP = new javax.swing.JTable();
        txbSearch = new javax.swing.JTextField();
        btnChangeDataSource = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnF5 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        lbTotal = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        tbIP.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ManHinh", "Ram", "Cpu", "Gpu", "TrongLuong", "LoaiOCung", "DungLuong", "Gia", "Ten", "Class"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tbIP);

        txbSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txbSearchKeyReleased(evt);
            }
        });

        btnChangeDataSource.setText("ChangeDataTraining");
        btnChangeDataSource.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChangeDataSourceActionPerformed(evt);
            }
        });

        jLabel1.setText("Filter:");

        btnF5.setText("Refresh");
        btnF5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnF5ActionPerformed(evt);
            }
        });

        jLabel2.setText("Total:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 682, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txbSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbTotal)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnF5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnChangeDataSource)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnChangeDataSource)
                    .addComponent(txbSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(btnF5)
                    .addComponent(jLabel2)
                    .addComponent(lbTotal))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 443, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txbSearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txbSearchKeyReleased
        RowFilter<Object, Object> filter = new RowFilter<Object, Object>() {
            public boolean include(RowFilter.Entry entry) {
                return entry.getStringValue(8).toLowerCase().contains(txbSearch.getText().toLowerCase());
            }
        };
        TableRowSorter<TableModel> sorter = new TableRowSorter<TableModel>(tbIP.getModel());
        sorter.setRowFilter(filter);
        tbIP.setRowSorter(sorter);
    }//GEN-LAST:event_txbSearchKeyReleased

    private void btnChangeDataSourceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChangeDataSourceActionPerformed
        JFileChooser jfc = new JFileChooser(FileSystemView.getFileSystemView().getHomeDirectory());

        int returnValue = jfc.showOpenDialog(null);
        // int returnValue = jfc.showSaveDialog(null);

        if (returnValue == JFileChooser.APPROVE_OPTION) {
            File selectedFile = jfc.getSelectedFile();
            Setting.GetSettingData().setFileData(selectedFile.getAbsolutePath());
            KMeansModel.build();
            main.save = true;
            init();
            JOptionPane.showMessageDialog(this, "File data laptop training has change to " + selectedFile.getAbsolutePath());

        }
    }//GEN-LAST:event_btnChangeDataSourceActionPerformed

    private void btnF5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnF5ActionPerformed
        init();
    }//GEN-LAST:event_btnF5ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnChangeDataSource;
    private javax.swing.JButton btnF5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbTotal;
    private javax.swing.JTable tbIP;
    private javax.swing.JTextField txbSearch;
    // End of variables declaration//GEN-END:variables
}
