/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Main;

import Model.KMeansModel;
import Model.Setting;
import java.io.File;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;
import javax.swing.RowFilter;
import javax.swing.filechooser.FileSystemView;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;
import weka.core.Instance;
import weka.core.Instances;

/**
 *
 * @author dttr2
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public boolean save = false;

    public Main() {
        initComponents();
        init();
    }

    public void init() {
        HashMap dataLaptopInStore = Setting.GetLaptopInStoreVector().getData();
        DefaultTableModel tbModel1 = (DefaultTableModel) tbIP.getModel();
        tbModel1.setRowCount(0);
        for (Object value : dataLaptopInStore.values()) {
            String[] vector = (String[]) value;
            tbModel1.addRow(vector);
        }
        lbFileTest.setText(Setting.GetSettingData().getFileDataLaptopInStore());
        lbFileTraining.setText(Setting.GetSettingData().getFileData());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        btnOk = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        lbClass = new javax.swing.JLabel();
        tbResult = new javax.swing.JScrollPane();
        tbRS = new javax.swing.JTable();
        jLabel10 = new javax.swing.JLabel();
        lbTotal = new javax.swing.JLabel();
        btnAdd = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbIP = new javax.swing.JTable();
        btnF5 = new javax.swing.JButton();
        txbSearch = new javax.swing.JTextField();
        btnView = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnStatus = new javax.swing.JButton();
        btnDataSource = new javax.swing.JButton();
        btnDel = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnSave = new javax.swing.JButton();
        btnChangeDataTest = new javax.swing.JButton();
        btnChangeDataTraining = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        lbFileTest = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lbFileTraining = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        btnOk.setText("OK");
        btnOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOkActionPerformed(evt);
            }
        });

        jLabel9.setText("Class:");

        tbRS.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ManHinh", "Ram", "Cpu", "Gpu", "TrongLuong", "LoaiBoNho", "DungLuong", "Gia", "Ten", "Id"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbResult.setViewportView(tbRS);

        jLabel10.setText("Total:");

        lbTotal.setText("0");

        btnAdd.setText("Add");
        btnAdd.setToolTipText("");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        tbIP.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ManHinh", "Ram", "Cpu", "Gpu", "TrongLuong", "LoaiOCung", "DungLuong", "Gia", "Ten", "Id"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbIP.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jScrollPane1.setViewportView(tbIP);

        btnF5.setText("Refresh");
        btnF5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnF5ActionPerformed(evt);
            }
        });

        txbSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txbSearchKeyReleased(evt);
            }
        });

        btnView.setText("View");
        btnView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewActionPerformed(evt);
            }
        });

        btnEdit.setText("Edit");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        btnStatus.setText("Status");
        btnStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStatusActionPerformed(evt);
            }
        });

        btnDataSource.setText("Data");
        btnDataSource.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDataSourceActionPerformed(evt);
            }
        });

        btnDel.setText("Remove");
        btnDel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDelActionPerformed(evt);
            }
        });

        jLabel1.setText("Filter:");

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnChangeDataTest.setText("ChangeDataTest");
        btnChangeDataTest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChangeDataTestActionPerformed(evt);
            }
        });

        btnChangeDataTraining.setText("ChangeDataTraining");
        btnChangeDataTraining.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChangeDataTrainingActionPerformed(evt);
            }
        });

        jLabel2.setText("File data test:");

        jLabel3.setText("File data training:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tbResult)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbClass)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbTotal)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnOk))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txbSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 86, Short.MAX_VALUE)
                        .addComponent(btnChangeDataTest)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnChangeDataTraining)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSave)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEdit)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnView)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnDel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnDataSource)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnStatus)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnF5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAdd)
                        .addGap(4, 4, 4)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbFileTest)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbFileTraining)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnDel, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txbSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnF5)
                        .addComponent(btnAdd)
                        .addComponent(btnEdit)
                        .addComponent(btnStatus)
                        .addComponent(btnDataSource)
                        .addComponent(btnView)
                        .addComponent(jLabel1)
                        .addComponent(btnSave)
                        .addComponent(btnChangeDataTest)
                        .addComponent(btnChangeDataTraining)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(btnOk))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lbClass)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel9)
                                .addComponent(jLabel10)
                                .addComponent(lbTotal)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tbResult, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(lbFileTest)
                    .addComponent(jLabel3)
                    .addComponent(lbFileTraining))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOkActionPerformed
        try {
            Instances data = KMeansModel.data_p;
            Instance ins = KMeansModel.data_p.lastInstance();
            HashMap dataLaptopInStore = Setting.GetLaptopInStoreVector().getData();
            HashMap h = Setting.GetLaptopInStoreVector().getHeader();
            String laptopId = tbIP.getValueAt(tbIP.getSelectedRow(), 9).toString();
            String[] laptopVector = (String[]) dataLaptopInStore.get("" + laptopId);

            ins.setValue(data.attribute("manhinh"), Double.valueOf(laptopVector[(int) h.get("manhinh")]));
            ins.setValue(data.attribute("ram"), Double.valueOf(laptopVector[(int) h.get("ram")]));
            ins.setValue(data.attribute("cpu"), Double.valueOf(laptopVector[(int) h.get("cpu")]));
            ins.setValue(data.attribute("gpu"), Double.valueOf(laptopVector[(int) h.get("gpu")]));
            ins.setValue(data.attribute("trongluong"), Double.valueOf(laptopVector[(int) h.get("trongluong")]));
            ins.setValue(data.attribute("loaibonho"), Double.valueOf(laptopVector[(int) h.get("loaibonho")]));
            ins.setValue(data.attribute("dungluongbonho"), Double.valueOf(laptopVector[(int) h.get("dungluongbonho")]));
            ins.setValue(data.attribute("gia"), Double.valueOf(laptopVector[(int) h.get("gia")]));

            int clus = KMeansModel.model.clusterInstance(ins);
            DefaultTableModel tbModel = (DefaultTableModel) tbRS.getModel();
            tbModel.setRowCount(0);

            lbClass.setText(KMeansModel.classes[clus]);

            int c = 0;
            for (Object value : dataLaptopInStore.values()) {
                String[] vector = (String[]) value;

                ins.setValue(data.attribute("manhinh"), Double.valueOf(vector[(int) h.get("manhinh")]));
                ins.setValue(data.attribute("ram"), Double.valueOf(vector[(int) h.get("ram")]));
                ins.setValue(data.attribute("cpu"), Double.valueOf(vector[(int) h.get("cpu")]));
                ins.setValue(data.attribute("gpu"), Double.valueOf(vector[(int) h.get("gpu")]));
                ins.setValue(data.attribute("trongluong"), Double.valueOf(vector[(int) h.get("trongluong")]));
                ins.setValue(data.attribute("loaibonho"), Double.valueOf(vector[(int) h.get("loaibonho")]));
                ins.setValue(data.attribute("dungluongbonho"), Double.valueOf(vector[(int) h.get("dungluongbonho")]));
                ins.setValue(data.attribute("gia"), Double.valueOf(vector[(int) h.get("gia")]));

                if ((int) KMeansModel.model.clusterInstance(ins) == clus) {
                    c++;
                    tbModel.addRow(vector);
                }

            }
            lbTotal.setText("" + c);
            JOptionPane.showMessageDialog(this, "Class: " + lbClass.getText() + "\nTotal: " + c);
        } catch (Exception ex) {
            Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, "Lỗi! " + ex.getMessage());
        }

    }//GEN-LAST:event_btnOkActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        (new AddRow(0, "", this)).show();
    }//GEN-LAST:event_btnAddActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        if (save) {
            btnSaveActionPerformed(null);
        }
    }//GEN-LAST:event_formWindowClosing

    private void btnF5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnF5ActionPerformed
//        KMeansModel.build();
        init();
//        btnOkActionPerformed(null);
    }//GEN-LAST:event_btnF5ActionPerformed

    private void txbSearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txbSearchKeyReleased
        RowFilter<Object, Object> filter = new RowFilter<Object, Object>() {
            public boolean include(RowFilter.Entry entry) {
                return entry.getStringValue(8).toLowerCase().contains(txbSearch.getText().toLowerCase());
            }
        };

        TableRowSorter<TableModel> sorter = new TableRowSorter<TableModel>(tbIP.getModel());
        sorter.setRowFilter(filter);
        tbIP.setRowSorter(sorter);
    }//GEN-LAST:event_txbSearchKeyReleased

    private void btnStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStatusActionPerformed
        // create a JTextArea
        JTextArea textArea = new JTextArea(26, 65);
        textArea.setText(KMeansModel.clsEval.clusterResultsToString());
        textArea.setEditable(false);
        JScrollPane scrollPane = new JScrollPane(textArea);
        JOptionPane.showMessageDialog(this, scrollPane);
    }//GEN-LAST:event_btnStatusActionPerformed

    private void btnViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewActionPerformed
        String id = "";
        if (tbIP.getSelectedRow() >= 0) {
            id = tbIP.getValueAt(tbIP.getSelectedRow(), 9).toString();
            (new AddRow(1, id, this)).show();
        }else{
            JOptionPane.showMessageDialog(this, "Không có hàng nào được chọn!");
        }
    }//GEN-LAST:event_btnViewActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        String id = "";
        if (tbIP.getSelectedRow() >= 0) {
            id = tbIP.getValueAt(tbIP.getSelectedRow(), 9).toString();
            (new AddRow(2, id, this)).show();
        }else{
            JOptionPane.showMessageDialog(this, "Không có hàng nào được chọn!");
        }
    }//GEN-LAST:event_btnEditActionPerformed

    private void btnDataSourceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDataSourceActionPerformed
        (new DataS(this)).show();
    }//GEN-LAST:event_btnDataSourceActionPerformed

    private void btnDelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDelActionPerformed
        String id = "";
        if (tbIP.getSelectedRow() >= 0) {
            id = String.valueOf(tbIP.getModel().getValueAt(tbIP.getSelectedRow(), 9));
            int input = JOptionPane.showOptionDialog(null, "Dữ liệu đã xóa không thể phục hồi!", "Remove", JOptionPane.OK_CANCEL_OPTION, JOptionPane.WARNING_MESSAGE, null, null, null);
            if (input == JOptionPane.OK_OPTION) {
                DAO.removeRowFromDataProduct(id);
                JOptionPane.showMessageDialog(this, "Thành công!");
                this.init();
                save = true;
            }
        }else{
            JOptionPane.showMessageDialog(this, "Không có hàng nào được chọn!");
        }

    }//GEN-LAST:event_btnDelActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        if (!save) {
            JOptionPane.showMessageDialog(this, "Không có dữ liệu thay đổi!");
            return;
        }
        int input = JOptionPane.showOptionDialog(null, "Bạn có muốn lưu thay đổi vào file data?", "Save", JOptionPane.OK_CANCEL_OPTION, JOptionPane.WARNING_MESSAGE, null, null, null);
        if (input == JOptionPane.OK_OPTION) {
            if (saveToFile()) {
                JOptionPane.showMessageDialog(this, "Đã lưu!");
                save = false;
            } else {
                JOptionPane.showMessageDialog(this, "Xãy ra lỗi trong quá trình lưu file, xem file log để biết thêm chi tiết!");
            }
        }
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnChangeDataTestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChangeDataTestActionPerformed
        JFileChooser jfc = new JFileChooser(FileSystemView.getFileSystemView().getHomeDirectory());

        int returnValue = jfc.showOpenDialog(null);
        // int returnValue = jfc.showSaveDialog(null);

        if (returnValue == JFileChooser.APPROVE_OPTION) {
            File selectedFile = jfc.getSelectedFile();
            Setting.GetSettingData().setFileDataLaptopInStore(selectedFile.getAbsolutePath());
            Setting.setLaptopInStoreVector(null);
            init();
            save = true;
            JOptionPane.showMessageDialog(this, "File data laptop in store has change to " + selectedFile.getAbsolutePath());

        }
    }//GEN-LAST:event_btnChangeDataTestActionPerformed

    private void btnChangeDataTrainingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChangeDataTrainingActionPerformed
        JFileChooser jfc = new JFileChooser(FileSystemView.getFileSystemView().getHomeDirectory());

        int returnValue = jfc.showOpenDialog(null);
        // int returnValue = jfc.showSaveDialog(null);

        if (returnValue == JFileChooser.APPROVE_OPTION) {
            File selectedFile = jfc.getSelectedFile();
            Setting.GetSettingData().setFileData(selectedFile.getAbsolutePath());
            KMeansModel.build();
            save = true;
            JOptionPane.showMessageDialog(this, "File data laptop training has change to " + selectedFile.getAbsolutePath());

        }
    }//GEN-LAST:event_btnChangeDataTrainingActionPerformed

    private boolean saveToFile() {

        return Setting.GetLaptopInfo().saveToCsv(Setting.GetSettingData().getFileProduct())
                && Setting.GetLaptopInStoreVector().saveToCsv(Setting.GetSettingData().getFileDataLaptopInStore())
                && Setting.WriteData();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnChangeDataTest;
    private javax.swing.JButton btnChangeDataTraining;
    private javax.swing.JButton btnDataSource;
    private javax.swing.JButton btnDel;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnF5;
    private javax.swing.JButton btnOk;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnStatus;
    private javax.swing.JButton btnView;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lbClass;
    private javax.swing.JLabel lbFileTest;
    private javax.swing.JLabel lbFileTraining;
    private javax.swing.JLabel lbTotal;
    private javax.swing.JTable tbIP;
    private javax.swing.JTable tbRS;
    private javax.swing.JScrollPane tbResult;
    private javax.swing.JTextField txbSearch;
    // End of variables declaration//GEN-END:variables
}
