/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Main;

import Model.KMeansModel;
import Model.MySQLConnUtils;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;
import weka.core.Instance;
import weka.core.Instances;

/**
 *
 * @author dttr2
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
        init();
    }

    void init() {
        Instances data = KMeansModel.data_t;
        DefaultTableModel tbModel1 = (DefaultTableModel) tbIP.getModel();
        tbModel1.setRowCount(0);
        int ipL = data.size();
        for (int i = 0; i < ipL; i++) {
            tbModel1.addRow(new Object[]{
                data.get(i).value(data.attribute("manhinh")),
                data.get(i).value(data.attribute("ram")),
                data.get(i).value(data.attribute("cpu")),
                data.get(i).value(data.attribute("gpu")),
                data.get(i).value(data.attribute("trongluong")),
                data.get(i).value(data.attribute("loaibonho")),
                data.get(i).value(data.attribute("dungluongbonho")),
                data.get(i).value(data.attribute("gia")),
                data.get(i).stringValue(data.attribute("laptop")),
                data.get(i).stringValue(data.attribute("class")),
                data.get(i).value(data.attribute("laptopid"))
            });
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        btnOk = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        lbClass = new javax.swing.JLabel();
        tbResult = new javax.swing.JScrollPane();
        tbRS = new javax.swing.JTable();
        jLabel10 = new javax.swing.JLabel();
        lbTotal = new javax.swing.JLabel();
        btnAdd = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbIP = new javax.swing.JTable();
        btnF5 = new javax.swing.JButton();
        txbSearch = new javax.swing.JTextField();
        btnView = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnStatus = new javax.swing.JButton();
        btnDataSource = new javax.swing.JButton();
        btnDel = new javax.swing.JButton();
        btnFormatData = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        btnOk.setText("OK");
        btnOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOkActionPerformed(evt);
            }
        });

        jLabel9.setText("Class:");

        tbRS.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ManHinh", "Ram", "Cpu", "Gpu", "TrongLuong", "LoaiOCung", "DungLuong", "Gia", "Class", "Ten", ""
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbResult.setViewportView(tbRS);

        jLabel10.setText("Total:");

        lbTotal.setText("0");

        btnAdd.setText("Add");
        btnAdd.setToolTipText("");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        tbIP.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ManHinh", "Ram", "Cpu", "Gpu", "TrongLuong", "LoaiOCung", "DungLuong", "Gia", "Ten", "Class", "Id"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbIP.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jScrollPane1.setViewportView(tbIP);

        btnF5.setText("Refresh");
        btnF5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnF5ActionPerformed(evt);
            }
        });

        txbSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txbSearchKeyReleased(evt);
            }
        });

        btnView.setText("View");
        btnView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewActionPerformed(evt);
            }
        });

        btnEdit.setText("Edit");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        btnStatus.setText("Status");
        btnStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStatusActionPerformed(evt);
            }
        });

        btnDataSource.setText("Data");
        btnDataSource.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDataSourceActionPerformed(evt);
            }
        });

        btnDel.setText("Remove");
        btnDel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDelActionPerformed(evt);
            }
        });

        btnFormatData.setText("Format data");
        btnFormatData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFormatDataActionPerformed(evt);
            }
        });

        jButton1.setText("ChangeDB");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tbResult, javax.swing.GroupLayout.DEFAULT_SIZE, 798, Short.MAX_VALUE)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbClass)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbTotal)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnOk))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(txbSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnFormatData)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnDel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnDataSource)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnStatus)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEdit)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnView)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnF5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAdd)
                        .addGap(4, 4, 4)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txbSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnF5)
                    .addComponent(btnAdd)
                    .addComponent(btnView)
                    .addComponent(btnEdit)
                    .addComponent(btnStatus)
                    .addComponent(btnDataSource)
                    .addComponent(btnDel)
                    .addComponent(btnFormatData)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(btnOk))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lbClass)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel9)
                                .addComponent(jLabel10)
                                .addComponent(lbTotal)))))
                .addGap(10, 10, 10)
                .addComponent(tbResult, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOkActionPerformed
        try {

            Instances data_t = KMeansModel.data_t;
            Instances data_t_p = KMeansModel.data_t_p;

            Instance ins = data_t_p.get(tbIP.getSelectedRow());

            int clus = KMeansModel.model.clusterInstance(ins);
            DefaultTableModel tbModel = (DefaultTableModel) tbRS.getModel();
            tbModel.setRowCount(0);

            lbClass.setText(KMeansModel.classes[clus]);

            int c = 0;
            for (int i = 0; i < data_t_p.size(); i++) {
                if ((int) KMeansModel.model.clusterInstance(data_t_p.get(i)) == clus) {
                    c++;
                    tbModel.addRow(new Object[]{
                        data_t.get(i).value(data_t.attribute("manhinh")),
                        data_t.get(i).value(data_t.attribute("ram")),
                        data_t.get(i).value(data_t.attribute("cpu")),
                        data_t.get(i).value(data_t.attribute("gpu")),
                        data_t.get(i).value(data_t.attribute("trongluong")),
                        data_t.get(i).value(data_t.attribute("loaibonho")),
                        data_t.get(i).value(data_t.attribute("dungluongbonho")),
                        data_t.get(i).value(data_t.attribute("gia")),
                        lbClass.getText(),
                        data_t.get(i).stringValue(data_t.attribute("laptop")),
                        data_t.get(i).value(data_t.attribute("laptopid"))
                    });
                }

            }
            lbTotal.setText("" + c);
        } catch (Exception ex) {
            Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_btnOkActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        (new AddRow(0, 0)).show();
    }//GEN-LAST:event_btnAddActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing

    }//GEN-LAST:event_formWindowClosing

    private void btnF5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnF5ActionPerformed
        KMeansModel.build();
        init();
//        btnOkActionPerformed(null);
    }//GEN-LAST:event_btnF5ActionPerformed

    private void txbSearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txbSearchKeyReleased
        RowFilter<Object, Object> filter = new RowFilter<Object, Object>() {
            public boolean include(RowFilter.Entry entry) {
                return entry.getStringValue(8).toLowerCase().contains(txbSearch.getText().toLowerCase());
            }
        };

        TableRowSorter<TableModel> sorter = new TableRowSorter<TableModel>(tbIP.getModel());
        sorter.setRowFilter(filter);
        tbIP.setRowSorter(sorter);
    }//GEN-LAST:event_txbSearchKeyReleased

    private void btnStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStatusActionPerformed
        // create a JTextArea
        JTextArea textArea = new JTextArea(26, 65);
        textArea.setText(KMeansModel.clsEval.clusterResultsToString());
        textArea.setEditable(false);
        JScrollPane scrollPane = new JScrollPane(textArea);
        JOptionPane.showMessageDialog(this, scrollPane);
    }//GEN-LAST:event_btnStatusActionPerformed

    private void btnViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewActionPerformed
        String id = null;
        if (tbIP.getSelectedRow() >= 0) {
            id = tbIP.getValueAt(tbIP.getSelectedRow(), 10).toString();
            (new AddRow(1, Double.valueOf(id))).show();
        }
//        else if(tbRS.getSelectedRow()>=0){
//            id=tbRS.getModel().getValueAt(tbIP.getSelectedRow(), 10).toString();
//        }


    }//GEN-LAST:event_btnViewActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        String id = null;
        if (tbIP.getSelectedRow() >= 0) {
            id = tbIP.getValueAt(tbIP.getSelectedRow(), 10).toString();
            (new AddRow(2, Double.valueOf(id))).show();
        }
    }//GEN-LAST:event_btnEditActionPerformed

    private void btnDataSourceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDataSourceActionPerformed
        (new DataS()).show();
    }//GEN-LAST:event_btnDataSourceActionPerformed

    private void btnDelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDelActionPerformed
        double id = -1;
        if (tbIP.getSelectedRow() >= 0) {
            id = Double.valueOf(String.valueOf(tbIP.getModel().getValueAt(tbIP.getSelectedRow(), 10)));
            int input = JOptionPane.showOptionDialog(null, "Dữ liệu đã xóa không thể phục hồi!", "Remove", JOptionPane.OK_CANCEL_OPTION, JOptionPane.WARNING_MESSAGE, null, null, null);

            if (input == JOptionPane.OK_OPTION) {
                try {
                    DAO.removeRow(id);
                    JOptionPane.showMessageDialog(this, "Thành công!");
                } catch (SQLException ex) {
                    Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
                    JOptionPane.showMessageDialog(this, "Lỗi!");
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
                     JOptionPane.showMessageDialog(this, "Lỗi!");
                }
            }
        }

    }//GEN-LAST:event_btnDelActionPerformed

    private void btnFormatDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFormatDataActionPerformed
        try {
            KMeansModel.formatData();
            KMeansModel.build();
            this.init();
            JOptionPane.showMessageDialog(this, "Thành công!");
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Lỗi!");
            Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(this, "Lỗi!");
            Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnFormatDataActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        (new ChangeDBConnection()).show();       // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnDataSource;
    private javax.swing.JButton btnDel;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnF5;
    private javax.swing.JButton btnFormatData;
    private javax.swing.JButton btnOk;
    private javax.swing.JButton btnStatus;
    private javax.swing.JButton btnView;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lbClass;
    private javax.swing.JLabel lbTotal;
    private javax.swing.JTable tbIP;
    private javax.swing.JTable tbRS;
    private javax.swing.JScrollPane tbResult;
    private javax.swing.JTextField txbSearch;
    // End of variables declaration//GEN-END:variables
}
